### ISSUE TITLE
Th class library will be deleted when the model is enforced created

### ISSUE THREAD

**Issue by limingxinleo** [phalcon/phalcon-devtools#1009]
### Details
* The model
~~~
namespace MyApp\Models;

use limx\phalcon\DB;

class Book extends \Phalcon\Mvc\Model
{
~~~
When I enforced created the model by devtools. My library will be deleted.
* The result
~~~
namespace MyApp\Models;

class Book extends \Phalcon\Mvc\Model
{

~~~

Environment::

  OS: Darwin MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
  PHP Version: 7.0.17
  PHP SAPI: cli
  PHP Bin: /usr/local/Cellar/php70/7.0.17_9/bin/php
  PHP Extension Dir: /usr/local/Cellar/php70/7.0.17_9/lib/php/extensions/no-debug-non-zts-20151012
  PHP Bin Dir: /usr/local/Cellar/php70/7.0.17_9/bin
  Loaded PHP config: /usr/local/etc/php/7.0/php.ini
Versions::
  Phalcon DevTools Version: 3.1.2
  Phalcon Version: 3.1.2
  AdminLTE Version: 2.3.6

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue, because if file with model is exist - devtools throw exception like 'Error: The model file "someModel.php" already exists in models dir'.
Could you provide commands?
Have you used `--force`, `--output`?
Could you provide models dir path?


Phalcon DevTools Version - 3.2.0
Phalcon Version - 3.2.1

**Comment by limingxinleo** [comment]
yes,I used --force

**Comment by sergeysviridenko** [comment]
If you use command `--force` devtools will rewrite model that was created. This is not a but.
