### ISSUE TITLE
Project name and namespaces regexp issue

### ISSUE THREAD

**Issue by nastasache** [phalcon/phalcon-devtools#1025]
When try to create a modules type project, the project name is restricted by namespaces validator.
For example:
$ phalcon project --name www.mysite.com --type=modules
Error: Invalid namespace syntax!

Phalcon  3.1.2, PHP 7, Linux, Apache

**Comment by sergeyklay** [comment]
Actually it is not bug. Phalcon Devtools uses `--name` to create namespace.

**Comment by ararunaufc** [comment]
I was trying to create a project and stumbled upon this problem, but I had no clue why it happened until I saw this report. It would be best if the error message in this case was clearer, because nowhere in the command parameters' names or help we find a reference to namespaces.

Should a new issue be opened?
