### ISSUE TITLE
Possibility to change Namespace from command line

### ISSUE THREAD

**Issue by ph4r5h4d** [phalcon/phalcon-devtools#1052]
It would be great if it would be possible to change namespace of application (regardless of application type) from command line.

This is not a high priority NFR but it would be good if somewhere in the middle of development, someone consider this feature.

**Comment by sergeyklay** [comment]
Cc: @sergeysviridenko

**Comment by sergeysviridenko** [comment]
Could you provide more information about your proposition?

**Comment by f4rsh4d** [comment]
Sure,
For example we have a module named Frontend and the corresponding namespace is /MyCompany/Frontend/Controller 
It's possible to happen a typo or in some cases someone tries to change the module name or company name or anything so for a change we want our new namespace like /MyNewCompany/Front/Controller

Frameworks such as Laravel does have this ability in their command line (artisan) and it's called  app:name which changes all the namespaces across all related files.

This issue is not a must nor high priority, this is just a feature that could help developers in some cases.

Thanks for considering it.

**Comment by kornerita** [comment]
Hi,

First of all, I think this feature should be part of the [devtools](https://github.com/phalcon/phalcon-devtools) rather part of Phalcon itself.

Second, there is a lot of things that this would have to support, personally I manage all the classes in the model with an UML modeler [BoUML](http://www.bouml.fr) in which a change of namespace regarding the model it's quite easy, and would also be easy with the [devtools](https://github.com/phalcon/phalcon-devtools) as well.

The things that would not be easy to change are the coded namespaces such as the one you would encounter in a route definition, i.e:

```php
$r = new \Phalcon\Mvc\Router\Route(
   '/index',
   [
      'namespace' => '\MyCompany\Frontend\Controllers',
      'controller' => 'main',
      'action' => 'index'
   ] 
);

```
or in a loader declaration:
```php
$loader = new \Phalcon\Loader();
$loader->registerNamespaces([
   "MyCompany\Frontend\Controllers" => APP_PATH . '/controllers/',
]);
$loader->register();
```

Maybe in laravel it's easier since I believe it's a convention over coding framework that you drop things where they are supposed to be found, and I think that Phalcon doesn't have that conception concept.

Well this are just my thoughts.

Regards,
Federico.

**Comment by sergeysviridenko** [comment]
Thank you for reply. I'll think what can we do as soon as possible.

**Comment by Jeckerson** [comment]
Closing for now due personal opinion: "It can be mass replaced manually in any popular IDE nowadays".
