### ISSUE TITLE
Migration Run: Disable FK Checks Before Creating FKs and Updating Data

### ISSUE THREAD

**Issue by rabrowne85** [phalcon/phalcon-devtools#1188]
When running migrations with Foreign Keys defined, it's possible for the order of the migration files to be such that the referenced table does not exist yet. Most DBs have the capability to temporarily disable foreign key checks and then enable them again later on.

I'm suggesting that foreign keys be disabled after this line:
https://github.com/phalcon/phalcon-devtools/blob/f7d474ae5eb953729f2b9a3ebd58e799debc09c3/scripts/Phalcon/Mvc/Model/Migration.php#L696

And then enabled again at the end of the references section of code.

The only question would be about adding data to the tables as well, as this will need to be disabled and enabled here as well.

**Comment by sergeysviridenko** [comment]
@rabrowne85 It isn't a bug. Devtools provides tools to work this migration. Migration mustn't be depend on specific DB. I think enable/disable checking FK - isn't good way to solve this problem, because it specific situation and it isn't universal. We will try to implement other way - add FK after create/run migration in 4.0.x branch.
