### ISSUE TITLE
An unexpected error has occurred: Option config has't been defined

### ISSUE THREAD

**Issue by JoseB07** [phalcon/phalcon-devtools#1234]
please anybody can help me

I would thank you a lot
![gg](https://user-images.githubusercontent.com/40371013/41562066-2d05e484-7311-11e8-84c2-af41f2ea07b5.png)

**Comment by sebabaillet** [comment]
Same error here. Have you been able to solve it?

**Comment by JoseB07** [comment]
no :CC

**Comment by sergeysviridenko** [comment]
@sebabaillet @JoseB07 Could you take a look [here](https://github.com/phalcon/phalcon-devtools/issues/1154)

**Comment by sergeysviridenko** [comment]
@sebabaillet @JoseB07 Have you solved this problem?

**Comment by sebabaillet** [comment]
Left it unsolved and moved back to previous versión of devtools. Will try to solve in the future when I have more time available.

**Comment by KarenSlame** [comment]
me podrían ayudar con este error

**Comment by KarenSlame** [comment]
can you help me with this error

**Comment by sebabaillet** [comment]
Hello. I had to move forward with the project so went back to webtools 2.0. I’ll let you know when I find a solution for this. 

Regards,

Seba.

**Comment by ImTheJano** [comment]
I got the same problem.. did anybody solve it_

**Comment by rjbick** [comment]
The problem is webtools doesn't appear to be pulling custom config.php at the point of model creation.

Below is a crap hack since I'm to busy to fix it correctly:
in scripts/Phalcon/Builder/Model.php 
Change line 91 from:
$this->modelOptions->setOption('config', $this->modelOptions->getOption('config'));
to:
$this->modelOptions->setOption('config', include '[path to your custom config]');

One of these days I'll find the real problem.

**Comment by 6562680** [comment]
Just add damn extends \Phalcon\Di\Injectable to scripts/Phalcon/Builder/Component.php
then replace
```
$this->modelOptions->setOption('config', $this->modelOptions->getOption('config'));
```
to this
```
$this->modelOptions->setOption('config', $this->config);
```

**Comment by Jeckerson** [comment]
Fixed
