### ISSUE TITLE
 Problem with webtools interface Closed #1254

### ISSUE THREAD

**Issue by faublak** [phalcon/phalcon-devtools#1254]
I have a problem when viewing webtools.
It is installed on a local computer with windows 10, under xampp.

[
![error_webtools](https://user-images.githubusercontent.com/44176394/46971347-b6286e00-d089-11e8-8099-8eee214e7473.jpg)
](url)

**Comment by Style87** [comment]
I recently ran into this issue. The problem is the server isn't sending the css files. On nginx I had to modify the www.conf file to allow the .css extension then add a specific location block for .css files in my default.conf file. As you're using xampp and therefor I believe Apache you'll need to check apache configs and .htaccess files. Webtools tries to load the css/js from localhost/css/webtools.css and localhost/js/webtools.js. Ensure you can hit these uris and that their content type is correct.

**Comment by faublak** [comment]
Thank you @Style87 . But I solved this problem by adding the following lines to my name_project / app / config / config.php file

'baseUri'       =>'/project/',
'staticUri'     =>'/prpject/'

![error_webtools](https://user-images.githubusercontent.com/44176394/47272203-2a628600-d550-11e8-86c1-1cab412b12f1.jpg)
