### ISSUE TITLE
[QUESTION] How to pass selectDefinition option to the Scaffold builder ?

### ISSUE THREAD

**Issue by le51** [phalcon/phalcon-devtools#587]
Hi,

How to pass selectDefinition option to the Scaffold builder as used here https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Builder/Scaffold.php#L214 ?

**Comment by pro-git** [comment]
Incomplete code.
There is a lot of futile code in Model.php dealing with relations but nothing pass to Scaffold.php in order to build a select box at least for n-1 relations.
There is not even the code to show the name of the related data instead of id.
There are other peoples that ask for this, including on forum but no answer.
I guess nothing take phalcon-devtools seriously as developer tool.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
