### ISSUE TITLE
No findFirstById method 

### ISSUE THREAD

**Issue by vadim-job-hg** [phalcon/phalcon-devtools#637]
No findFirstById in autocomplete. I used 2.0.10 folder for external path. Redgards, Vadim.
http://clip2net.com/s/3we8NmM

**Comment by Green-Cat** [comment]
Actually that's by design, it's a "magic" method created based on property names. So for example if you have a property "status" on your model then findFirstByStatus() will be a valid method. If you want your IDE to pick up the method for auto complete you need to add them as a docblock to your method declaration like this: ``` * @method static YourModelClass|bool findFirstById($id)```
