### ISSUE TITLE
Add a --merge option to model build

### ISSUE THREAD

**Issue by makerlabs** [phalcon/phalcon-devtools#664]
Thanks to this flag rather then --force which is replacing the properties/methods (depends if you use set/get) , extend, use statements. It will leave them as they are and add additional properties/methods which are missing. It's very important feature if you use all-models to update all your models.

**Comment by victorwbuzz** [comment]
Sure! If you changed your database for some reason with foreign keys using --force doesnt update the initialize method (belongsTo, hasOne, haMany)

**Comment by sergeysviridenko** [comment]
@makerlabs  Problem with option `--merge` are how it can merge if part of code was changed, resolve conflicts and I guess developer must see  different between old code and new added code? Actually you can generate new model and merge after deep analyze old and new code.

**Comment by alexbusu** [comment]
I have encountered the same issue as @makerlabs - I also agree that it would be nice to keep "extra" data in Models (like constants, use statements in file head, use traits statements inside Model class body, later added methods, etc). 
As per @victorhramos comment, maybe relationship changes between the Models is easier to manage in Annotations (metadata) - I'm not sure how relationships are defined now for Models, but I guess this would be a pretty significant refactoring process.

**Comment by sergeysviridenko** [comment]
@alexbusu Could you explain what do mean `extra` data? This issue is connected to option `merge`. Let's separate them. Could you please create new issue with your proposition and detail description? Then we'll try to sort out it.

**Comment by alexbusu** [comment]
Sure, @sergeysviridenko 
![image](https://user-images.githubusercontent.com/4104165/34611322-e3855580-f21c-11e7-9751-14b49e963cce.png)
As the issue author says, the `use` statements are not preserved. From this before-and-after model generation diff image I notice the constants are not preserved either. Nor the phpdoc or random class comments.
Moreover the setters and getters are replaced (I think the issue author also mentions this).
![image](https://user-images.githubusercontent.com/4104165/34611526-d3f1ea74-f21d-11e7-8006-89aa11b1f25a.png)
:information_source: The `x` on the left column in the picture highlight the `before-regenerate` row value.
So, why `--merge` option would not leave the existing data in file/class, and only add the additionals, if any? And if one wants "fresh" data then could use `--force` + `before-and-after` diff tool to merge the relevant data (the developer job, as you mentioned).

**Comment by sergeysviridenko** [comment]
@alexbusu All data generating with snippet. generator creates some methods, I'd say model skeleton. I guess if your project is started earlier and your model already has some extra code, then model generating isn't need for you and you already have this methods. As I've said earlier merge option has many problem (a little bit part of them I've describe above) and require add huge module and big conversation with many experienced developers to resolve issues that can appear (for example if you had property `$fooBar`, and generator try to write `$foo_bar`? This can't be resole automatically and require manually resolve). Something like this can be added to generator but my own opinion this is extra and unnecessary functional for generator of skeleton, because it won't be useful for the most of developers. How do you think @sergeyklay?

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that. IMO it is hard to implement.
