### ISSUE TITLE
Cannot declare class Phalcon\Config, because the name is already in use

### ISSUE THREAD

**Issue by dellert** [phalcon/phalcon-devtools#695]
When I set phalcon model --name test command or other phalcon command, I have error:

Cannot declare class Phalcon\Config, because the name is already in use in /phalcon/devtools/ide/stubs/Phalcon/Config.php on line 27

**Comment by matusch** [comment]
Any idea why it happens?

**Comment by sergeyklay** [comment]
I'll try to sort out as soon as I can

**Comment by frickenate** [comment]
Stumbled across the same issue, narrowed it down to problems with the `\Phalcon\Commands\Command::getConfig()` method. The logic for loading a config file initially looks for a `app/config/config.*` file, then `config/config.*`. If not found, it goes so far as to recursively search the entire project's directory structure for any file named `config.php` (case-insensitive, also .ini/.json/.yaml extensions). This can wind up finding the `vendor/phalcon/devtools/ide/stubs/Phalcon/Config.php` file.

The fix for most people is to plant their main config file at `config/config.php` or `app/config/config.php` (or .ini/.json/.yaml). Otherwise, you must pass the config file manually with each command using the `--config` option.

**Comment by sergeyklay** [comment]
@frickenate Thanks
