### ISSUE TITLE
Error version in class name when generate migration

### ISSUE THREAD

**Issue by mzf** [phalcon/phalcon-devtools#768]
```
phalcon migration generate
```
In migrations folder i see new migration with name 1.0.4, but all files has class names with postfix - 103.
Example: `user.php` - has class name `User_103`, but migration version - `1.0.4`.

_Environment:
Phalcon Dev Tools - 3.0.1
Phalcon - 3.0.0
Php - 7.0.8
OS - Win7_

**Comment by therosco** [comment]
We've got the same problem.

**Comment by therosco** [comment]
`object(Phalcon\Version\IncrementalItem)#28 (3) {
  ["_version":"Phalcon\Version\IncrementalItem":private]=>
  string(5) "1.0.3"
  ["_versionStamp":"Phalcon\Version\IncrementalItem":private]=>
  int(102)
  ["_parts":"Phalcon\Version\IncrementalItem":private]=>
  array(3) {
    [0]=>
    string(1) "1"
    [1]=>
    string(1) "0"
    [2]=>
    string(1) "2"
  }
}`

**Comment by frickenate** [comment]
Same problem, PHP 7 and Phalcon 3.0.0 with latest GitHub pull of the devtools. To clarify, the reason this is a critical bug rather than a minor visual glitch is because the first two migrations both get classes with "_100" in them, resulting in a redefined class error when trying to run them.

### migrations/1.0.0/user.php
```
class TestMigration_100 extends Migration
```

### migrations/1.0.1/user.php
```
class TestMigration_100 extends Migration
```

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.

**Comment by frickenate** [comment]
@sergeyklay Do you know if it's possible to have composer.json refer to an arbitrary git branch? Setting the version to `3.0.x` or `3.0.x-dev` seems to pulling an outdated packagist bundle that doesn't contain the updates. Tried a `repositories` section, but I can't seem to get a branch/version to actually work.

If I git clone directly, it works. Is it possible to have a simple composer.json definition instead of manually cloning?

**Comment by sergeyklay** [comment]
@frickenate May be it is Composer cache related issue or something in Packagist part. Try
```sh
composer require phalcon/devtools:3.0.x-dev#90287081f719d292f0381fa5c359eb5cea7384c2
```

http://stackoverflow.com/questions/21314381/how-to-correctly-require-a-specific-commit-in-composer-so-that-it-would-be-avail
